### ISSUE TITLE
Infinite loop issue

### ISSUE THREAD

**Issue by robmonte** [rsn-INVU/pre-eoc-xp-drops#2]
Not sure what changed with Runelite, but recently something has made this plugin start calling drawXpLabel way too often.
https://github.com/rsn-INVU/pre-eoc-xp-drops/blob/master/src/main/java/com/preeocxp/PreEocXpOverlay.java#L284

You can catch this by running Runelite in debug mode with the plugin enabled. I noticed that lines like the one below were being spammed about 50-100 times per second in my debug log:
`2022-08-02 19:52:54 [Client] DEBUG client-patch - getSkillExperience called for OVERALL!`

This is causing a performance impact to the client.

**Comment by rsn-INVU** [comment]
I will take a look at this and see if I can replicate and find the problem! Thanks for writing a report!

**Comment by robmonte** [comment]
I think what's happening is the drawXpLabel is getting called every game frame rendered. I believe Runelite lets you use an event subscription to only redraw when the player gains XP.

Example: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java#L381

**Comment by rsn-INVU** [comment]
You’re right. I’m using event subscriptions for most everything else, so I’ll see whether there was a specific reason it didn’t work here, or whether it was just an oversight. 

Good catch 👍

edit: Should in theory be an easy fix. Will take some time the coming week to sort this out, mostly to make sure I don’t add any new problems 😅

**Comment by rsn-INVU** [comment]
> I think what's happening is the drawXpLabel is getting called every game frame rendered. I believe Runelite lets you use an event subscription to only redraw when the player gains XP.
> 
> Example: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpTrackerPlugin.java#L381

Alright so I did some work on this.
What I've done is to only fetch the xp of the displayed skill when Xp is gained, or when the Config is updated (technically this could be made to only fetch when the displayed skill of choice is updated, but you'd have to be spamming the config settings quite hard to ever be able to tell a difference 😂)

Drawing has to be done for every frame, because it needs to be visible - but also for the xp drops themselves to function properly - fetching the xp from the client 50+ times a second is, however, unnecessary.

Does it sound like this addresses your problem? Let me know and I'll publish!

**Comment by robmonte** [comment]
Sounds good to me. I'm assuming only fetching for your displayed skill also includes "Overall"?

**Comment by rsn-INVU** [comment]
Overall is fetched once per game tick, indiscriminately. I believe there were issues with instances and quick hopping otherwise, causing it not to load properly, or to result in xp drops every time an instance was entered/left.  edit: yeah you get some problems when switching accounts and stuff like that.

**Comment by robmonte** [comment]
Sounds good, thanks for the updates!
